[package]
name = "indexer-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "indexer_rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merkle-tree = { git = "https://github.com/personaelabs/merkle-tree", rev = "d5f1b386e92f1e5306c6e9749db1ca529cae44cc" }
prost = "0.10.1"
prost-types = "0.10.0"
bytes = "1.1.0"
num-bigint = "0.4.4"
tokio = { version = "1.36.0", features = ["full"] }
dotenv = "0.15.0"
futures = "0.3.30"
rayon = "1.8.1"
rocksdb = { version = "0.22.0", default-features = false, features = [
    "snappy",
    "multi-threaded-cf",
] }
tokio-retry = "0.3"
tokio-postgres = { version = "0.7.10" }
num-format = "0.4.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0.114"
hex = "0.4.3"
serde = "1.0.197"
backoff = "0.4.0"
colored = "2.1.0"

[build-dependencies]
prost-build = "0.10.1"
