use crate::{
    contract::{Contract, ContractType},
    eth_rpc::Chain,
};

pub fn erc721_contracts() -> Vec<Contract> {
    vec![
        Contract {
            id: 0,
            address: "0x5Af0D9827E0c53E4799BB226655A1de152A425a5".to_string(),
            symbol: "MIL".to_string(),
            name: "Milady".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 13090020,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xed5af388653567af2f388e6224dc7c4b3241c544".to_string(),
            symbol: "AZUKI".to_string(),
            name: "Azuki".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 13975838,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xbd3531da5cf5857e7cfaa92426877b022e612cf8".to_string(),
            symbol: "PPG".to_string(),
            name: "Pudgy Penguins".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 12876179,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03".to_string(),
            symbol: "NOUN".to_string(),
            name: "Nouns".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 12985438,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d".to_string(),
            symbol: "BAYC".to_string(),
            name: "Bored Ape Yacht Club".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 12985438,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x60E4d786628Fea6478F785A6d7e704777c86a7c6".to_string(),
            symbol: "MAYC".to_string(),
            name: "Mutant Ape Yacht Club".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 13117018,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x8821bee2ba0df28761afff119d66390d594cd280".to_string(),
            symbol: "DEGODS".to_string(),
            name: "DeGods".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 16940173,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e".to_string(),
            symbol: "DOODLE".to_string(),
            name: "Doodles".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 13430097,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xdA1bf9B5De160cecdE3f9304B187a2F5F5b83707".to_string(),
            symbol: "CHRONOPHOTO".to_string(),
            name: "Chronophotograph".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 17160816,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x7Bd29408f11D2bFC23c34f18275bBf23bB716Bc7".to_string(),
            symbol: "meebits".to_string(),
            name: "Meebits".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 12358080,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x9ef8750c72061edbeeef4beb1aceee5b5a63748a".to_string(),
            symbol: "The187".to_string(),
            name: "The187".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 17052667,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0x4E1f41613c9084FdB9E34E11fAE9412427480e56".to_string(),
            symbol: "TERRAFORMS".to_string(),
            name: "Terraforms".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 13823015,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xd3d9ddd0cf0a5f0bfb8f7fceae075df687eaebab".to_string(),
            symbol: "TEST".to_string(),
            name: "Remilio".to_string(),
            chain: Chain::Mainnet,
            deployed_block: 15323174,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
        Contract {
            id: 0,
            address: "0xa41273d9ecce19051e109d87431002fb1404d392".to_string(),
            symbol: "crypto-the-game".to_string(),
            name: "Crypto: The Game Players".to_string(),
            chain: Chain::Base,
            deployed_block: 11088633,
            target_groups: vec!["allHolders".to_string()],
            contract_type: ContractType::ERC721,
        },
    ]
}
