FROM node:18.17.0

WORKDIR /usr/src/app

# Install pnpm
RUN npm install -g pnpm

COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .

COPY packages/db packages/db
COPY packages/indexer packages/indexer
COPY packages/merkle-tree-rs packages/merkle-tree-rs
COPY scripts scripts

# Install dependencies
RUN pnpm i

CMD ["sh", "./scripts/start-indexer.sh"]