#previewsEnabled: true
services:
  - type: cron
    name: cred-indexer
    plan: pro plus
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    rootDir: ./
    branch: main
    schedule: '0 * * * *'
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: REDIS_URL
        fromService:
          type: redis
          name: cred
          property: connectionString
  - type: redis
    name: cred
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
      
databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: standard
    postgresMajorVersion: 15
