previewsEnabled: true
services:
  - type: worker
    name: credbot
    plan: pro
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F db migrate:prod
    startCommand: NODE_ENV=production pnpm -F cred_bot exec ts-node src/index.ts
    rootDir: ./
    buildFilter:
      paths:
        - packages/cred_bot/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
        - packages/indexer/**
        - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
  - type: worker
    name: cred-indexer
    plan: pro plus
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    preDeployCommand: sh ./predeploy.sh
    rootDir: ./
    buildFilter:
      paths:
        - packages/indexer-rs/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - fromGroup: cred
    disk:
      name: db
      mountPath: /usr/src/app/db      

      
databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro
    postgresMajorVersion: 15
