previewsEnabled: true
services:
  - type: worker
    name: cred-indexer
    plan: pro plus
    runtime: rust
    region: oregon
    rootDir: ./
    buildCommand: "cargo build --release --bin indexer-rs" 
    startCommand: "cargo run --release --bin indexer-rs"
    buildFilter:
      paths:
        - packages/indexer-rs/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
    disk:
      name: db
      mountPath: /db      

      
databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro
    postgresMajorVersion: 15
