services:
  - type: cron
    name: cred-indexer
    plan: standard
    runtime: docker
    region: oregon
    dockerfilePath: ./packages/indexer/Dockerfile
    rootDir: ./
    branch: main
    schedule: '0 * * * *'
    dockerCommand: sh ./scripts/setup-docker-cron.sh
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred

databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro
    postgresMajorVersion: 15    