services:
  - type: cron
    name: cred-indexer
    plan: pro plus
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    rootDir: ./
    branch: main
    schedule: '0 * * * *'
    dockerCommand: pnpm -F indexer exec ts-node ./src/indexMerkleTree.ts
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred

databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro
    postgresMajorVersion: 15    