previewsEnabled: true
services:
  - type: cron
    name: credbot
    plan: pro
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F db migrate:prod
    startCommand: NODE_ENV="production" pnpm -F cred_bot exec ts-node src/index.ts
    rootDir: ./
    schedule: '0 * * * *'
    buildFilter:
      paths:
        - packages/cred_bot/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
        - packages/indexer/**
        - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
  - type: cron
    name: cred-indexer
    plan: pro plus
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    preDeployCommand: pnpm -F db migrate:prod && pnpm -F indexer exec ts-node ./scripts/populate.ts
    rootDir: ./
    schedule: '0 * * * *'
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: REDIS_URL
        fromService:
          type: redis
          name: cred
          property: connectionString
  - type: redis
    plan: pro plus
    name: cred
    ipAllowList: []
      
databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro plus
    postgresMajorVersion: 15
