previewsEnabled: true
services:
  - type: web
    name: cred-frontend
    plan: pro
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F frontend build
    startCommand: NODE_ENV=production pnpm -F frontend start
    preDeployCommand: pnpm -F db migrate:prod
    buildFilter:
      paths:
        - packages/frontend/**
        - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: web
    name: credchat
    plan: pro
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F chat build
    startCommand: NODE_ENV=production pnpm -F chat start
    buildFilter:
      paths:
        - packages/chat/**
        - packages/shared/**
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_CHAIN
        value: "sepolia"
        previewValue: "sepolia"
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: web
    name: cred-indexer
    plan: pro plus
    previewPlan: starter
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    preDeployCommand: populate
    rootDir: ./
    buildFilter:
      paths:
        - packages/indexer-rs/**
        - packages/db/**
      ignoredPaths:
        - packages/notification/**
        - packages/circuit/**
        - packages/frontend/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - fromGroup: cred
    disk:
      name: db
      mountPath: /usr/src/app/db
  - type: worker
    name: credchat-sync
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F sync start
    rootDir: ./
    buildFilter:
      paths:
        - packages/sync/**
        - packages/shared/**
      ignoredPaths:
        - packages/app/**
        - packages/api/**
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: CHAIN
        value: "sepolia"
        previewValue: "sepolia"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: worker
    name: credchat-notifier
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F notification start
    rootDir: ./
    buildFilter:
      paths:
        - packages/notification/**
        - packages/shared/**
      ignoredPaths:
        - packages/chat/**
        - packages/app/**
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
