previewsEnabled: true
services:
  - type: web
    name: cred-frontend
    plan: pro
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F frontend build
    startCommand: NODE_ENV=production pnpm -F frontend start
    preDeployCommand: pnpm -F db migrate:prod
    pullRequestPreviewsEnabled: false
    autoDeploy: false
    buildFilter:
      paths:
        - packages/frontend/**
        - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: web
    name: credchat
    plan: pro
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F chat build
    startCommand: NODE_ENV=production pnpm -F chat start
    autoDeploy: false
    buildFilter:
      paths:
        - packages/chat/**/*
        - packages/shared/**/*
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_CHAIN
        value: "sepolia"
        previewValue: "sepolia"
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
      - key: NEXT_PUBLIC_PROJECT_ID
        value: "cred-279bb"
        previewValue: "staging-423405"
      - key: NEXT_PUBLIC_VAPID_KEY
        value: BHaVlakB8SbeMEprNB2e6FQtlPMFjyWEhMnBH8dKn-q2epYPi--NNCWM2EZmsjaXUQ0FbKpPuppmC-Od6xL0M88
        previewValue: BKF9U_p1O5RChiFe30w4bq-IcVTh-i0LcXHSpBUsELHuzfxsQlqhlqL9QfzjuavM_k1aWksZRbEuWQHkTid6J70
  - type: web
    name: cred-indexer
    plan: pro plus
    previewPlan: starter
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile.indexer
    preDeployCommand: populate
    pullRequestPreviewsEnabled: false
    rootDir: ./
    autoDeploy: false
    buildFilter:
      paths:
        - packages/indexer-rs/**/*
        - packages/db/**/**/*
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - fromGroup: cred
    disk:
      name: db
      mountPath: /usr/src/app/db
  - type: worker
    name: credchat-sync
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F sync start
    rootDir: ./
    autoDeploy: false
    buildFilter:
      paths:
        - packages/sync/**/*
        - packages/shared/**/*  
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: DATABASE_URL
        fromDatabase:
          name: cred
          property: connectionString
      - key: CHAIN
        value: "sepolia"
        previewValue: "sepolia"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: worker
    name: credchat-notifier
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F notification start
    rootDir: ./
    autoDeploy: false
    buildFilter:
      paths:
        - packages/notification/**/*
        - packages/shared/**/*
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account.json
        previewValue: /etc/secrets/firebase-service-account-staging.json
  - type: worker
    name: credchat-monkey
    plan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F monkey start
    rootDir: ./
    pullRequestPreviewsEnabled: false
    autoDeploy: false
    buildFilter:
      paths:
        - packages/monkey/**/*
        - packages/shared/**/*
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - fromGroup: cred
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase-service-account-staging.json

databases:
  - name: cred
    databaseName: cred
    region: oregon
    plan: pro
    previewPlan: starter
    postgresMajorVersion: 15
