[package]
name = "eth-membership"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-secq256k1 = "0.4.0"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
num-bigint = "0.4.4"
spartan = { path = "../../../../spartan-evm", features = ["profiler"] }
wasm-bindgen = "0.2.87"
ethers = "2.0.10"
