version: '3.8'
services:
  database:
    image: 'postgres:15'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=anon
      - POSTGRES_PASSWORD=iamanon
      - POSTGRES_DB=anon-boost
    volumes:
      - anon_boost_pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  anon_boost_pg_data:
