name: Deploy Firestore rules
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  db-config: 
    name: Update database rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Create service account key
        working-directory: ./packages/app
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > ./service-account.json
      - name: Apply security rules
        working-directory: ./packages/app
        run: firebase deploy --only firestore:default
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json